package com.lumentale.wiki.map;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.stereotype.Component;

import jakarta.annotation.PostConstruct;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.HashMap;
import java.util.Iterator;
import java.util.Map;
import java.util.Optional;

/**
 * Per-map tile-projection calibration, generated by
 * {@code tools/calibrate_map_tiles.py} into
 * {@code data/curated/map_tile_calibration.json}.
 *
 * Most baked tiles cover (3840 × MapScaleValue) world units centred on the
 * gameplay-bounds offset; a handful were rendered with a different framing, so
 * their markers drift off the terrain. For those maps the script fits the real
 * frame empirically (pins-on-art maximisation) and this index serves it; the
 * frame is attached to {@code MapDetail.Bounds} and preferred by the frontend.
 */
@Component
public class TileCalibrationIndex {

    private static final Logger log = LoggerFactory.getLogger(TileCalibrationIndex.class);

    /** centerX, centerZ, spanX, spanZ — the calibrated tile frame in world units. */
    public record Frame(double centerX, double centerZ, double spanX, double spanZ) {}

    private final ObjectMapper mapper;
    @Value("${lumentale.curated.dir:data/curated}") private String curatedDir;
    private Map<String, Frame> frames = Map.of();

    public TileCalibrationIndex(ObjectMapper mapper) { this.mapper = mapper; }

    public Optional<Frame> get(String mapGuid) { return Optional.ofNullable(frames.get(mapGuid)); }

    @PostConstruct
    void load() {
        Path file = Path.of(curatedDir, "map_tile_calibration.json");
        if (!Files.isRegularFile(file)) {
            log.info("TileCalibrationIndex: {} absent — all tiles use the default framing.", file);
            return;
        }
        try {
            JsonNode root = mapper.readTree(Files.readAllBytes(file));
            Map<String, Frame> out = new HashMap<>();
            for (Iterator<Map.Entry<String, JsonNode>> it = root.fields(); it.hasNext(); ) {
                Map.Entry<String, JsonNode> e = it.next();
                JsonNode v = e.getValue();
                out.put(e.getKey(), new Frame(
                    v.path("centerX").asDouble(), v.path("centerZ").asDouble(),
                    v.path("spanX").asDouble(), v.path("spanZ").asDouble()));
            }
            this.frames = out;
            log.info("TileCalibrationIndex: {} calibrated tile frames loaded.", out.size());
        } catch (Exception e) {
            log.warn("TileCalibrationIndex: cannot read {} — default framing for all tiles.", file, e);
        }
    }
}
