package com.lumentale.wiki.seed;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.node.ObjectNode;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.boot.CommandLineRunner;
import org.springframework.core.annotation.Order;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.stereotype.Component;
import org.springframework.transaction.annotation.Transactional;

import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Map;
import java.util.UUID;

import static com.lumentale.wiki.seed.SeedSupport.isEmpty;

/**
 * Seeds Module 14 ({@code curated_name}) from the name-resolved dataset
 * generated by {@code tools/build_curated_data.py}:
 * <ul>
 *   <li>{@code data/curated/names.json} — the master GUID index:
 *       {@code { guid → {name, kind} }} for every known entity (2.8k rows).</li>
 *   <li>{@code data/curated/camps.json} — per-camp extras (host map guid, map
 *       name, region) folded into the {@code extra} jsonb column.</li>
 * </ul>
 * Repositories LEFT JOIN {@code curated_name} and prefer its {@code name} over
 * dev codenames ({@code P01_CenterCampData}) and Italian raws.
 *
 * Keys that are not valid UUIDs (card pools keyed by name when the source guid
 * is blank) are skipped — they have no joinable identity in the schema.
 *
 * Idempotent: guarded by {@link SeedSupport#isEmpty} on {@code curated_name}.
 */
@Component
@Order(70)
public class CuratedNameSeeder implements CommandLineRunner {

    private static final Logger log = LoggerFactory.getLogger(CuratedNameSeeder.class);

    private final JdbcTemplate jdbc;
    private final ObjectMapper mapper;

    @Value("${lumentale.seed.on-empty:true}")     private boolean seedOnEmpty;
    @Value("${lumentale.curated.dir:data/curated}") private String curatedDir;

    public CuratedNameSeeder(JdbcTemplate jdbc, ObjectMapper mapper) {
        this.jdbc = jdbc;
        this.mapper = mapper;
    }

    @Override
    @Transactional
    public void run(String... args) {
        if (!seedOnEmpty) { log.info("CuratedNameSeeder: seeding disabled."); return; }
        if (!isEmpty(jdbc, "curated_name")) { log.info("  curated_name already seeded — skipping."); return; }

        Path names = Path.of(curatedDir, "names.json");
        if (!Files.isRegularFile(names)) {
            log.warn("CuratedNameSeeder: {} not found — curated_name NOT seeded. " +
                    "Run tools/build_curated_data.py to generate data/curated/.", names);
            return;
        }

        Map<String, ObjectNode> extras = campExtras();
        extras.putAll(mapExtras());

        JsonNode root = readRoot(names);
        List<Object[]> rows = new ArrayList<>(3000);
        int skipped = 0;
        for (Iterator<Map.Entry<String, JsonNode>> it = root.fields(); it.hasNext(); ) {
            Map.Entry<String, JsonNode> e = it.next();
            UUID guid = parseUuid(e.getKey());
            String name = e.getValue().path("name").asText(null);
            String kind = e.getValue().path("kind").asText(null);
            if (guid == null || name == null || name.isBlank() || kind == null) { skipped++; continue; }
            ObjectNode extra = extras.get(e.getKey());
            rows.add(new Object[]{ guid, kind, name, extra == null ? null : extra.toString() });
        }
        jdbc.batchUpdate(
            "INSERT INTO curated_name(guid,kind,name,extra) VALUES (?,?,?,?::jsonb) ON CONFLICT DO NOTHING",
            rows);
        log.info("  curated_name: {} rows ({} unjoinable keys skipped)", rows.size(), skipped);
    }

    /**
     * {map guid → {region}} from data/curated/maps.json — the REFINED region
     * taxonomy (hub = Magnolia city, center = the central wilderness ring,
     * prologue = Iris Hamlet; the engine's own north/south pass through). The
     * engine's RegionSide=0 maps to game_map.region NULL, so display queries
     * COALESCE through this extra.
     */
    private Map<String, ObjectNode> mapExtras() {
        Path maps = Path.of(curatedDir, "maps.json");
        Map<String, ObjectNode> out = new java.util.HashMap<>();
        if (!Files.isRegularFile(maps)) return out;
        for (JsonNode m : readRoot(maps)) {
            String guid = m.path("guid").asText(null);
            String region = m.path("region").asText(null);
            if (guid == null || region == null || region.isBlank()) continue;
            ObjectNode extra = mapper.createObjectNode();
            extra.put("region", region);
            out.put(guid, extra);
        }
        return out;
    }

    /** {camp guid → {map_guid, map_name, region}} from data/curated/camps.json. */
    private Map<String, ObjectNode> campExtras() {
        Path camps = Path.of(curatedDir, "camps.json");
        Map<String, ObjectNode> out = new java.util.HashMap<>();
        if (!Files.isRegularFile(camps)) return out;
        for (JsonNode c : readRoot(camps)) {
            String guid = c.path("guid").asText(null);
            if (guid == null) continue;
            ObjectNode extra = mapper.createObjectNode();
            for (String f : List.of("map_guid", "map_name", "region")) {
                if (c.hasNonNull(f)) extra.put(f, c.get(f).asText());
            }
            if (!extra.isEmpty()) out.put(guid, extra);
        }
        return out;
    }

    private static UUID parseUuid(String s) {
        try { return UUID.fromString(s); } catch (IllegalArgumentException e) { return null; }
    }

    private JsonNode readRoot(Path file) {
        try {
            return mapper.readTree(Files.readAllBytes(file));
        } catch (Exception e) {
            throw new IllegalStateException("Cannot read curated file " + file, e);
        }
    }
}
