-- ============================================================================
-- Module 14: curated display names — the name-resolved layer generated by
-- tools/build_curated_data.py (data/curated/names.json). One row per known
-- GUID with its real English display name, the entity kind, and optional
-- per-kind extras (e.g. a camp's host map + region). Repositories LEFT JOIN
-- this table and prefer curated_name.name over codenames / Italian raws.
-- Source: data/curated/names.json (+ data/curated/camps.json extras).
-- ============================================================================

CREATE TABLE curated_name (
    guid  uuid PRIMARY KEY,
    kind  text NOT NULL,                  -- form|species|move|item|map|boss|trainer|camp|…
    name  text NOT NULL,                  -- resolved English display name
    extra jsonb                           -- per-kind extras (camp: map_guid/region/map_name)
);
CREATE INDEX curated_name_kind_idx ON curated_name (kind);

-- Scalar helper so repository SQL can prefer the curated display name with a
-- one-term prefix: COALESCE(curated_display(x.guid), <legacy fallback expr>).
-- PK lookup per call; STABLE so the planner may cache within a statement.
CREATE FUNCTION curated_display(p_guid uuid) RETURNS text AS $$
    SELECT name FROM curated_name WHERE guid = p_guid
$$ LANGUAGE sql STABLE;

